#!/bin/bash

# A script to connect remotely to a jupyter notebook that has been started with the --no-browser 
# and --port=<insert port number> flags on a remote server.

# Where ever you save this file, add that directory to your $PATH, then restart your terminal.
# Once this is done, you should be able to execture `no-browser-jupyter` from the
# command line. 

# Author: Matthew DeVerna
# Date  : ~Nov. 2020 

# Ask for the server address
echo "What server are we going to be running our Jupyter Notebook from?"
echo "~~~> Please type something like: mdeverna@gh.luddy.indiana.edu"
read server

# What port?
echo "~~~~~~~~~~"
echo "And what port would you like to run on?"
echo "Please type something like: 8890"
read input_port

# Call the command
echo "~~~~~~~~~~"
echo "Connecting to port: ssh -N -f -L localhost:$input_port:localhost:$input_port $server"
ssh -N -f -L localhost:$input_port:localhost:$input_port $server
